---
title: "Covid19Japan.com"
output:
  html_document:
    code_folding : hide
    df_print: paged
    theme: cerulean
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      fig.width = 8, fig.height = 6)

require(tidyverse)
require(jsonlite)

lagdiff <- function(n) {
  n - dplyr::lag(n, default = 0L)
}

ma7 <- function(n) {
  zoo::rollmeanr(n, k = 7L, na.pad = TRUE)
}

ma28 <- function(n) {
  zoo::rollmeanr(n, k = 28L, na.pad = TRUE)
}

subtitle <- paste0("Generated @", lubridate::now())
caption <- "Data Source: covid19japan.com"
```


[Covid19 Japan](covid19japan.com)が独自に収集している陽性者単位のデータ（個票データ）。ソースとデータは全て[GitHub](https://github.com/reustle/covid19japan)にて公開されており、データはJSON形式。「レコード数 $\neq$ 累計陽性者数」であることに注意。

　  

# Import
[Covid19 Japan](covid19japan.com)が[GitHub](https://github.com/reustle/covid19japan)で公開しているデータは前述のようにJSON形式であり、最新データは`latest.json`ファイルで示されている。このため、読み込む際はひと工夫必要。


## 個票データ（Patient Data）
陽性者単位の個票データ。
```{r}
# path <- "https://raw.githubusercontent.com/reustle/covid19japan-data/master/docs/patient_data/"
# 
# df <- path %>% 
#   paste0("latest.json") %>% 
#   readr::read_lines() %>% 
#   paste0(path, .) %>% 
#   jsonlite::fromJSON()

df <- "https://raw.githubusercontent.com/reustle/covid19japan-data/master/docs/patient_data/latest.json" %>% 
  jsonlite::fromJSON()

df
```

　  

## Area Data
地域・地方ごとの分析を行う場合に便利な都道府県データを用意した。このデータは[Gist](https://gist.github.com/k-metrics/9f3fc18e042850ff24ad9676ac34764b)で公開している。
```{r, echo=FALSE, message=FALSE}
prefs <- "https://gist.githubusercontent.com/k-metrics/9f3fc18e042850ff24ad9676ac34764b/raw/9262c36b0740edd575e9f0292dad61c9cce269be/pref_utf8.csv" %>% 
  readr::read_csv() %>% 
  dplyr::rename(pcode = `コード`) %>% 
  dplyr::mutate(pref = stringr::str_to_title(pref),
                pcode = forcats::fct_inorder(pcode),
                fct_pref = forcats::fct_inorder(pref),
                `都道府県` = forcats::fct_inorder(`都道府県`),
                `八地方区分` = forcats::fct_inorder(`八地方区分`),
                `広域圏` = forcats::fct_inorder(`広域圏`),
                `通俗的区分` = forcats::fct_inorder(`通俗的区分`),
                `推計人口` = as.integer(`推計人口`))

prefs
```

　  

## Tidy & Transform
各変量（フィーチャー）を適切な形式に変換し、地域区分でも分析できるように都道府県データと結合することで、ベースとなるデータセットを作成する。なお、都道府県以外で報告されたレコードを除いている。
```{r}
x <- df %>% 
  dplyr::select(patientId, date = dateAnnounced, gender,
                detectedPrefecture, patientStatus, knownCluster,
                confirmedPatient,
                # charterFlightPassenger, cruisePassengerDisembarked,
                ageBracket,
                deceasedDate, deceasedReportedDate) %>% 
  # dplyr::filter(date < lubridate::today()) %>% 
  dplyr::filter(confirmedPatient == TRUE) %>% 
  # dplyr::mutate(date = lubridate::as_date(date),
  #               gender = forcats::as_factor(gender),
  #               patientStatus = forcats::as_factor(patientStatus),
  #               cluster = dplyr::if_else(!is.na(knownCluster), TRUE, FALSE),
  #               ageBracket = forcats::as_factor(ageBracket),
  #               deceasedDate = lubridate::as_date(deceasedDate),
  #               deceasedReportedDate = lubridate::as_date(deceasedReportedDate)) %>% 
  dplyr::left_join(prefs, by = c("detectedPrefecture" = "pref")) %>% 
  # dplyr::select(-`推計人口`, -pref) %>%
  # dplyr::select(pref) %>%
  dplyr::rename(pref = `都道府県`, region = `八地方区分`, popu = `推計人口`) %>% 
  dplyr::select(-pcode, -`広域圏`, -`通俗的区分`, -fct_pref)
  # tidyr::drop_na(pref)

x

x %>% 
  readr::write_csv(paste0("./Covid19/covid19japan_", lubridate::today(), ".csv"))
```

　  
