---
title: "Covid19Japan.com"
output:
  html_document:
    code_folding : hide
    df_print: paged
    theme: cerulean
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE,
                      fig.width = 8, fig.height = 6)

require(tidyverse)
require(jsonlite)

lagdiff <- function(n) {
  n - dplyr::lag(n, default = 0L)
}

ma7 <- function(n) {
  zoo::rollmeanr(n, k = 7L, na.pad = TRUE)
}

ma28 <- function(n) {
  zoo::rollmeanr(n, k = 28L, na.pad = TRUE)
}

subtitle <- paste0("Generated @", lubridate::now())
caption <- "Data Source: covid19japan.com"
```


（はじめに）

　  

# Import


## 個票データ
```{r, include=FALSE, eval=FALSE}
sig_df <- "https://docs.google.com/spreadsheets/d/10MFfRQTblbOpuvOs_yjIYgntpMGBg592dL8veXoPpp4" %>% 
  googlesheets4::read_sheet(sheet = "罹患者", col_types = "c")

sig_df

# df %>%
#   readr::write_csv(paste0("./Covid19/SIGNATE_CaseData_", lubridate::today(), ".csv"),
#                    na = "")
```



## 集計データ
```{r, include=FALSE, eval=FALSE}
df_s <- "https://docs.google.com/spreadsheets/d/10MFfRQTblbOpuvOs_yjIYgntpMGBg592dL8veXoPpp4" %>% 
  googlesheets4::read_sheet(sheet = "統計全般", col_types = "c")

df_s

# df_s %>% 
#   readr::write_csv(paste0("./Covid19/SIGNATE_CaseData_Daily_", lubridate::today(), ".csv"), na = "")
```



## 都道府県別集計データ
"Messy"な日次集計データ
```{r, include=FALSE, eval=FALSE}
df_ps <- "https://docs.google.com/spreadsheets/d/10MFfRQTblbOpuvOs_yjIYgntpMGBg592dL8veXoPpp4" %>% 
  googlesheets4::read_sheet(sheet = "罹患者統計", col_types = "c")

df_ps

# df_ps %>% 
#   readr::write_csv(paste0("./Covid19/SIGNATE_CaseData_Messy_", lubridate::today(), ".csv"), na = "")
```


